DROP TABLE tbl_book;
CREATE TABLE tbl_book (
    BOOK_SEQ	NUMBER	PRIMARY KEY,
    BOOK_ISBN	CHAR(13)	NOT NULL,	
    BOOK_TITLE	nVARCHAR2(100)	NOT NULL,
    BOOK_AUTHOR	nVARCHAR2(100),
    BOOK_COMP	nVARCHAR2(100),
    BOOK_DATE	nVARCHAR2(10),	
    BOOK_PAGE	NUMBER,	
    BOOK_PRICE	NUMBER,		
    BOOK_DESCRIPTION	nVARCHAR2(2000),		
    BOOK_IMAGE	nVARCHAR2(1000),		
    BOOK_STOCK	NUMBER(5)		
);
DROP SEQUENCE SEQ_BOOK;

UPDATE tbl_book SET book_page = 300 WHERE book_page is NULL;
CREATE SEQUENCE SEQ_BOOK
START WITH 300
INCREMENT BY 1;

DROP TABLE tbl_user;
CREATE TABLE tbl_user (
    USER_SEQ	NUMBER	PRIMARY KEY,
    USER_ID     nVARCHAR2(100)	NOT	NULL,
    USER_PASS   nVARCHAR2(100)	NOT	NULL,
    USER_NAME	nVARCHAR2(100)	NOT	NULL,
    USER_BIRTH	CHAR(10)		,
    USER_SEX	CHAR(1)	,	
    USER_PHONE	nVARCHAR2(100)	NOT NULL,	
    USER_EMAIL	nVARCHAR2(1000)		,
    USER_IMAGE	nVARCHAR2(125)		,
    USER_RENT_COUNT	NUMBER	,	
    USER_RENT_TOTAL	NUMBER ,
    USER_ROLE	NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_USER
START WITH 1
INCREMENT BY 1;

DROP TABLE tbl_rent;
CREATE TABLE tbl_order (
    ORDER_SEQ	NUMBER	PRIMARY KEY,
    ORDER_USER_ID	nVARCHAR2(100)	NOT	NULL,
    ORDER_USER_NAME	nVARCHAR2(100)	NOT	NULL,
    ORDER_USER_PHONE	nVARCHAR2(100)	NOT NULL,	
    ORDER_USER_ADDR	nVARCHAR2(1000)	NOT NULL,
    ORDER_BOOK_ISBN	CHAR(13)	NOT NULL,
    ORDER_BOOK_TITLE	nVARCHAR2(100)	NOT NULL,
    ORDER_BOOK_COMP	nVARCHAR2(100),
    ORDER_BOOK_PRICE	NUMBER,
    ORDER_BOOK_STOCK	NUMBER(5),
    ORDER_DATE	CHAR(10)	NOT	NULL, -- 주문일
    ORDER_PAYMENT_DATE	CHAR(10)	NOT	NULL, -- 결제일
    ORDER_PAYMENT_WAY	nVARCHAR2(10)	NOT	NULL, -- 결제방법
    ORDER_STATE	nVARCHAR2(100)	NOT	NULL -- 주문상태(결제완료, 상품발송, 배송중, 배송완료)
);

DROP SEQUENCE SEQ_RENT;
CREATE SEQUENCE SEQ_RENT
START WITH 1
INCREMENT BY 1;

UPDATE tbl_user SET user_role = 1;
SELECT * FROM tbl_book;
SELECT * FROM tbl_user;
commit;