-- °ü¸®ÀÚ (IOLIST)
CREATE TABLESPACE iolistTS
DATAFILE 'D:\bizwork\ordata\iolist.dbf'
SIZE 100M AUTOEXTEND ON NEXT 100K;

CREATE USER iolist IDENTIFIED BY 1234
DEFAULT TABLESPACE iolistTS;

GRANT DBA TO iolist;